In [1]:
import torch

In [2]:
w =  torch.tensor(3.0, requires_grad=True)
b = torch.tensor(1.0,requires_grad=True)


In [3]:
def forward(x):
    y = w*x +b
    return y
    

In [6]:
x= torch.tensor([[4],[7]])

In [7]:
forward(x)

tensor([[13.],
        [22.]], grad_fn=<AddBackward0>)

## Linear Class

In [8]:
import torch

In [9]:
from torch.nn import Linear

In [10]:
torch.manual_seed(1)

In [11]:
model  = Linear(in_features=1, out_features = 1)

In [13]:
print(model.bias,model.weight)

Parameter containing:
tensor([-0.4414], requires_grad=True) Parameter containing:
tensor([[0.5153]], requires_grad=True)


In [16]:
x = torch.tensor([[2.0],[3.3]])
model(x)

tensor([[0.5891],
        [1.2590]], grad_fn=<AddmmBackward0>)