In [1]:
import torch

In [5]:
one_d= torch.arange(start=0, end=9, step=1)
one_d

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
two_d = one_d.view(3,-1)

In [8]:
two_d

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [9]:
two_d.dim()

2

In [10]:
two_d[0,0]

tensor(0)

In [11]:
two_d[1,2]

tensor(5)

In [12]:
x = torch.arange(0,18)

In [13]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [14]:
x.view(2,3,3)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])

In [15]:
x.view(3,2,3)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])